/* Generated by Amaranth Yosys 0.10.0 (PyPI ver 0.10.0.dev47, git sha1 dca8fb54a) */

(* \amaranth.hierarchy  = "top" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module top(ovf, clk, rst, en);
  reg \initial  = 0;
  (* src = "c:\\Users\\fcost\\OneDrive\\Documentos\\GitHub\\New-Repositories\\Amaranth\\scripts\\up_counter.py:34" *)
  wire \$1 ;
  (* src = "c:\\Users\\fcost\\OneDrive\\Documentos\\GitHub\\New-Repositories\\Amaranth\\scripts\\up_counter.py:40" *)
  wire [16:0] \$3 ;
  (* src = "c:\\Users\\fcost\\OneDrive\\Documentos\\GitHub\\New-Repositories\\Amaranth\\scripts\\up_counter.py:40" *)
  wire [16:0] \$4 ;
  (* src = "C:\\Users\\fcost\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\amaranth\\hdl\\ir.py:527" *)
  input clk;
  (* src = "c:\\Users\\fcost\\OneDrive\\Documentos\\GitHub\\New-Repositories\\Amaranth\\scripts\\up_counter.py:29" *)
  reg [15:0] count = 16'h0000;
  (* src = "c:\\Users\\fcost\\OneDrive\\Documentos\\GitHub\\New-Repositories\\Amaranth\\scripts\\up_counter.py:29" *)
  reg [15:0] \count$next ;
  (* src = "c:\\Users\\fcost\\OneDrive\\Documentos\\GitHub\\New-Repositories\\Amaranth\\scripts\\up_counter.py:25" *)
  input en;
  (* src = "c:\\Users\\fcost\\OneDrive\\Documentos\\GitHub\\New-Repositories\\Amaranth\\scripts\\up_counter.py:26" *)
  output ovf;
  (* src = "C:\\Users\\fcost\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\amaranth\\hdl\\ir.py:527" *)
  input rst;
  assign \$1  = count == (* src = "c:\\Users\\fcost\\OneDrive\\Documentos\\GitHub\\New-Repositories\\Amaranth\\scripts\\up_counter.py:34" *) 5'h19;
  assign \$4  = count + (* src = "c:\\Users\\fcost\\OneDrive\\Documentos\\GitHub\\New-Repositories\\Amaranth\\scripts\\up_counter.py:40" *) 1'h1;
  always @(posedge clk)
    count <= \count$next ;
  always @* begin
    if (\initial ) begin end
    \count$next  = count;
    (* src = "c:\\Users\\fcost\\OneDrive\\Documentos\\GitHub\\New-Repositories\\Amaranth\\scripts\\up_counter.py:36" *)
    casez (en)
      /* src = "c:\\Users\\fcost\\OneDrive\\Documentos\\GitHub\\New-Repositories\\Amaranth\\scripts\\up_counter.py:36" */
      1'h1:
          (* full_case = 32'd1 *)
          (* src = "c:\\Users\\fcost\\OneDrive\\Documentos\\GitHub\\New-Repositories\\Amaranth\\scripts\\up_counter.py:37" *)
          casez (ovf)
            /* src = "c:\\Users\\fcost\\OneDrive\\Documentos\\GitHub\\New-Repositories\\Amaranth\\scripts\\up_counter.py:37" */
            1'h1:
                \count$next  = 16'h0000;
            /* src = "c:\\Users\\fcost\\OneDrive\\Documentos\\GitHub\\New-Repositories\\Amaranth\\scripts\\up_counter.py:39" */
            default:
                \count$next  = \$4 [15:0];
          endcase
    endcase
    (* src = "C:\\Users\\fcost\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\amaranth\\hdl\\xfrm.py:519" *)
    casez (rst)
      1'h1:
          \count$next  = 16'h0000;
    endcase
  end
  assign \$3  = \$4 ;
  assign ovf = \$1 ;
endmodule
